Transfer Gateway/DPoSV2 Config
ShipChain/hydra pull request #18
Opened 2019-04-16 20:47 UTC by ajhodges

This PR primarily addresses the need to include a loom.yaml config file with each node (#16). Additionally, the first node in a newly provisioned network will be designated as the transfer gateway oracle. The transfer gateway oracle _must_ be provisioned with an Ethereum private key that matches the address designated as the oracle in the mainnet gateway contract. Once the network is up, every initially provisioned node is whitelisted by the (DPoS) oracle and registered as a validator.

Other changes include:

- Addition of a Route53 DNS entry - {network-name}.network.shipchain.io
- Addition of an application load balancer pointing to all of the initial shipchain nodes for use in the dashboard, or any dapps.
- Configurable parameters for loom, transfer gateway, and DPoS
- ICMP traffic is opened to the nodes, addressing #15 
- Security groups/network ACLs cleaned up
- Lint issues
- Light refactoring

2019-04-16 20:50 UTC, ajhodges commented
Network provisioning with these changes looks something like this:
```
hydra network provision --name hydra-testing -s 3 -v 2.0.0+b963
hydra network publish --name hydra-testing --version 2.0.0+b963
hydra network configure --name hydra-testing --oracle-priv-key oracle_eth_priv.key
```
with `oracle_eth_priv.key` being the Ethereum private key mentioned above.

2019-04-16 21:11 UTC, mlclay requested changes
Worked with Adam testing these changes over the last week with different provisioned networks.  I like the changes and know they work well.  Minor refactor for readability.

2019-04-16 21:11 UTC, mlclay commented on hydra/helpers/client.py
> +        if kwargs['oracle'] if 'oracle' in kwargs else False:
For the sake of keeping this growing method easier to read, can we extract this Oracle loom.yaml setup to its own method `_setup_oracle_loom_yaml`?

2019-04-17 04:30 UTC, leewardbound commented
W/r/t the Oracle key note -- I'm aware that the genesis.json needs a specific Oracle key, but when I asked about it, Loom replied that actually, every node is a TG oracle, not just 1 of them, and they behave as a multisig on the mainnet TG contract.

I assume the singular key that the genesis.json file requires is just to bootstrap the other validators, perhaps, adding them to the list of multisig addresses on the mainnet contract; but in the name of science, we need to consult w/ their team and figure out what relevance setting the initial oracle key actually has, and what-if-anything other nodes need to do w/r/t TG oracle keys.

Other than that, these changes look fantastic, very impressive work done ahead of schedule, thanks!

2019-04-17 04:31 UTC, leewardbound approved these changes

2019-04-18 22:29 UTC, mlclay approved these changes

2019-04-19 00:09 UTC, merged